[package]
name = "img2ascii"
version = "0.1.0"
authors = ["anatolii"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
term_size = "0.3.2"
clap = "2.33.3"